# Creation of array

In [2]:
my_list = [1,2,3,4,5,6]
print (my_list)

[1, 2, 3, 4, 5, 6]


In [3]:
import numpy as np

In [4]:
array = np.array (my_list, dtype = int)
print (array)

[1 2 3 4 5 6]


In [5]:
print (type(array))
print (len(array))
print (array.ndim)
print (array.shape)

<class 'numpy.ndarray'>
6
1
(6,)


In [6]:
array2 = array.reshape (3, 2)
print (array2)
array2 . shape

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

In [7]:
array3 = array. reshape (3,-1)
print (array3)
print (array3. ndim)

[[1 2]
 [3 4]
 [5 6]]
2


In [8]:
## Initializing numpy arrays from nested Python lists

my_list2 = [1,2,3,4,5]
my_list3 = [2,3,4,5,6]
my_list4 = [9,7,6,8,9]

mul_arr = np.array([my_list2, my_list3, my_list4])

print(mul_arr)
print(mul_arr.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
(3, 5)


In [9]:
mul_arr. reshape (1, 15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

# Numpy Attributes

In [10]:
a = np.array([[1,2,3],[4,5,6]])
print (a. shape)

(2, 3)


In [11]:
# reshaping the ndarray
a . shape
print (a)

[[1 2 3]
 [4 5 6]]


In [12]:
# Reshape function to resize an array
b = a. reshape (3, 2)
print (b)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
r = range (24)

In [14]:
print (r)

range(0, 24)


In [15]:
# an array of evenly spaced numbers
a = np.arange (24)
print (a)
print (a . ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [16]:
# Reshaping the array 'a '
b = a. reshape (6,4,1)
print (b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


## NumPy Arthemetic operations

In [17]:
x = np.array([[1,2],[3,4]], dtype= np.float64 )
y = np.array([[5,6],[7,8]], dtype= np.float64 )
print (x)
print (y) 

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [18]:
print (x + y)
print (np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [19]:
print (x - y)
print (np.subtract (x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [20]:
print (x * y)
print (np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [21]:
print (x. dot (y) )
print (np.dot (x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [22]:
print (x / y)
print (np.divide (x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [23]:
print (np . sum (x))                                     # Compute overall sum (axis-None)

10.0


In [24]:
print (np.sum(x, axis=0))                                # Compute sum of each column

[4. 6.]


In [25]:
print (np. sum (x,axis=1))                               # Compute sum of each row

[3. 7.]
